---
http_interactions:
- request:
    method: post
    uri: "<DOCKER_HOST>/v1.16/build"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.17.0
      Content-Type:
      - application/tar
      Transfer-Encoding:
      - chunked
      X-Registry-Config:
      - eyJjb25maWdzIjp7Imh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxIjp7InVzZXJuYW1lIjoidGR1ZmZpZWxkIiwicGFzc3dvcmQiOiJpOUJmPkpndmZialkvc0pXTWNVOSIsImVtYWlsIjoiZ2l0aHViQHRvbWR1ZmZpZWxkLmNvbSJ9fX0=
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Tue, 16 Dec 2014 22:02:39 GMT
    body:
      encoding: UTF-8
      string: "{\"stream\":\"Step 0 : FROM debian:wheezy\\n\"}\r\n{\"stream\":\" ---\\u003e
        f6fab3b798be\\n\"}\r\n{\"stream\":\"Step 1 : ADD / /\\n\"}\r\n{\"stream\":\"
        ---\\u003e 7a0664009e78\\n\"}\r\n{\"stream\":\"Removing intermediate container
        7933f81f7b84\\n\"}\r\n{\"stream\":\"Successfully built 7a0664009e78\\n\"}\r\n"
    http_version: 
  recorded_at: Tue, 16 Dec 2014 22:02:39 GMT
- request:
    method: post
    uri: "<DOCKER_HOST>/v1.16/containers/create"
    body:
      encoding: UTF-8
      string: '{"Image":"7a0664009e78","Cmd":["cat","/Dockerfile"]}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.17.0
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Tue, 16 Dec 2014 22:02:40 GMT
      Content-Length:
      - '90'
    body:
      encoding: UTF-8
      string: |
        {"Id":"4bbd3c8f461099eda6e22946e80b24bccd6111939e4e27a02a212b3a1b020d09","Warnings":null}
    http_version: 
  recorded_at: Tue, 16 Dec 2014 22:02:39 GMT
- request:
    method: post
    uri: "<DOCKER_HOST>/v1.16/containers/4bbd3c8f461099eda6e22946e80b24bccd6111939e4e27a02a212b3a1b020d09/wait"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.17.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Tue, 16 Dec 2014 22:02:40 GMT
      Content-Length:
      - '17'
    body:
      encoding: UTF-8
      string: |
        {"StatusCode":0}
    http_version: 
  recorded_at: Tue, 16 Dec 2014 22:02:40 GMT
- request:
    method: delete
    uri: "<DOCKER_HOST>/v1.16/containers/4bbd3c8f461099eda6e22946e80b24bccd6111939e4e27a02a212b3a1b020d09"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.17.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 204
      message: 
    headers:
      Date:
      - Tue, 16 Dec 2014 22:02:40 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 16 Dec 2014 22:02:40 GMT
- request:
    method: delete
    uri: "<DOCKER_HOST>/v1.16/images/7a0664009e78?noprune=true"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.17.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Tue, 16 Dec 2014 22:02:40 GMT
      Content-Length:
      - '81'
    body:
      encoding: UTF-8
      string: |-
        [{"Deleted":"7a0664009e78aca62c1c553887a7ff3424c6ae5893b51297a9e78e778d2329c1"}
        ]
    http_version: 
  recorded_at: Tue, 16 Dec 2014 22:02:40 GMT
recorded_with: VCR 2.9.3
