---
http_interactions:
- request:
    method: post
    uri: "<DOCKER_HOST>/v1.16/build"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.23.0
      Content-Type:
      - application/tar
      Transfer-Encoding:
      - chunked
      X-Registry-Config:
      - eyJjb25maWdzIjp7Imh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxIjp7InVzZXJuYW1lIjoiZGViYmllX2RvY2tlciIsInBhc3N3b3JkIjoiKioqKioqKioqKioqKiIsImVtYWlsIjoiZGViYmllX2RvY2tlckBleGFtcGxlLmNvbSJ9fX0=
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Server:
      - Docker/1.9.0 (linux)
      Date:
      - Fri, 20 Nov 2015 16:40:40 GMT
    body:
      encoding: UTF-8
      string: "{\"stream\":\"Step 1 : FROM debian:wheezy\\n\"}\r\n{\"stream\":\" ---\\u003e
        b4c4e8b590a7\\n\"}\r\n{\"stream\":\"Step 2 : ADD . /\\n\"}\r\n{\"stream\":\"
        ---\\u003e Using cache\\n\"}\r\n{\"stream\":\" ---\\u003e 8c897ece9aad\\n\"}\r\n{\"stream\":\"Successfully
        built 8c897ece9aad\\n\"}\r\n"
    http_version: 
  recorded_at: Fri, 20 Nov 2015 16:40:40 GMT
- request:
    method: delete
    uri: "<DOCKER_HOST>/v1.16/images/8c897ece9aad?noprune=true"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.23.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 409
      message: 
    headers:
      Content-Type:
      - text/plain; charset=utf-8
      Server:
      - Docker/1.9.0 (linux)
      Date:
      - Fri, 20 Nov 2015 16:40:40 GMT
      Content-Length:
      - '113'
    body:
      encoding: UTF-8
      string: |
        conflict: unable to delete 8c897ece9aad (must be forced) - image is being used by stopped container eca55c72e3d7
    http_version: 
  recorded_at: Fri, 20 Nov 2015 16:40:40 GMT
recorded_with: VCR 3.0.0
