---
http_interactions:
- request:
    method: get
    uri: http://localhost:4243/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: ''
    headers:
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        YXBwbGljYXRpb24vanNvbg==
      !binary "RGF0ZQ==":
      - !binary |-
        V2VkLCAxOSBKdW4gMjAxMyAyMDo1OToxMiBHTVQ=
      !binary "VHJhbnNmZXItRW5jb2Rpbmc=":
      - !binary |-
        Y2h1bmtlZA==
    body:
      encoding: US-ASCII
      string: ! '{"Debug":false,"Containers":187,"Images":196,"NFd":10,"NGoroutines":9,"MemoryLimit":true}'
    http_version: 
  recorded_at: Wed, 19 Jun 2013 20:59:12 GMT
recorded_with: VCR 2.5.0
