---
http_interactions:
- request:
    method: get
    uri: http://localhost:4243/v1.4/info
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - text/plain
      User-Agent:
      - Swipely/Docker-API 1.3.1
  response:
    status:
      code: 200
      message: ''
    headers:
      Content-Type:
      - application/json
      Content-Length:
      - '166'
      Date:
      - Wed, 07 Aug 2013 16:52:53 GMT
    body:
      encoding: UTF-8
      string: '{"Debug":false,"Containers":87,"Images":15,"NFd":19,"NGoroutines":20,"MemoryLimit":true,"LXCVersion":"0.7.5","NEventsListener":182,"KernelVersion":"3.8.0-19-generic"}'
    http_version: 
  recorded_at: Wed, 07 Aug 2013 16:52:53 GMT
recorded_with: VCR 2.4.0
