---
http_interactions:
- request:
    method: get
    uri: "<DOCKER_HOST>/v1.16/info"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.23.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Server:
      - Docker/1.9.0 (linux)
      Date:
      - Fri, 20 Nov 2015 16:40:41 GMT
      Content-Length:
      - '1850'
    body:
      encoding: UTF-8
      string: |
        {"ID":"OG3O:S3DS:PZAH:3PWH:GE5F:XLOQ:NJHR:TIXF:HM4O:DJJM:H767:7SXM","Containers":8,"Images":80,"Driver":"devicemapper","DriverStatus":[["Pool Name","docker-253:2-1577924-pool"],["Pool Blocksize","65.54 kB"],["Base Device Size","10.74 GB"],["Backing Filesystem","extfs"],["Data file","/dev/loop0"],["Metadata file","/dev/loop1"],["Data Space Used","5.445 GB"],["Data Space Total","107.4 GB"],["Data Space Available","12.51 GB"],["Metadata Space Used","5.788 MB"],["Metadata Space Total","2.147 GB"],["Metadata Space Available","2.142 GB"],["Udev Sync Supported","true"],["Deferred Removal Enabled","false"],["Deferred Deletion Enabled","false"],["Deferred Deleted Device Count","0"],["Data loop file","/var/lib/docker/devicemapper/devicemapper/data"],["Metadata loop file","/var/lib/docker/devicemapper/devicemapper/metadata"],["Library Version","1.02.107 (2015-09-05)"]],"MemoryLimit":true,"SwapLimit":true,"CpuCfsPeriod":true,"CpuCfsQuota":true,"IPv4Forwarding":true,"BridgeNfIptables":true,"BridgeNfIp6tables":true,"Debug":false,"NFd":24,"OomKillDisable":true,"NGoroutines":55,"SystemTime":"2015-11-20T17:40:41.067763018+01:00","ExecutionDriver":"native-0.2","LoggingDriver":"json-file","NEventsListener":0,"KernelVersion":"4.2.6-300.fc23.x86_64","OperatingSystem":"Fedora 23 (Workstation Edition)","IndexServerAddress":"https://index.docker.io/v1/","RegistryConfig":{"InsecureRegistryCIDRs":["127.0.0.0/8"],"IndexConfigs":{"docker.io":{"Name":"docker.io","Mirrors":null,"Secure":true,"Official":true}},"Mirrors":null},"InitSha1":"1015e63dc758671b4237050624c87cfc36a84e6d","InitPath":"/usr/libexec/docker/dockerinit","NCPU":4,"MemTotal":4082241536,"DockerRootDir":"/var/lib/docker","HttpProxy":"","HttpsProxy":"","NoProxy":"","Name":"lampone","Labels":null,"ExperimentalBuild":false,"ServerVersion":"1.9.0","ClusterStore":"","ClusterAdvertise":""}
    http_version: 
  recorded_at: Fri, 20 Nov 2015 16:40:41 GMT
recorded_with: VCR 3.0.0
