---
http_interactions:
- request:
    method: get
    uri: "<DOCKER_HOST>/v1.16/info"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.17.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Job-Name:
      - info
      Date:
      - Tue, 16 Dec 2014 22:02:40 GMT
      Content-Length:
      - '666'
    body:
      encoding: UTF-8
      string: |
        {"Containers":8,"Debug":1,"DockerRootDir":"/mnt/sda1/var/lib/docker","Driver":"aufs","DriverStatus":[["Root Dir","/mnt/sda1/var/lib/docker/aufs"],["Dirs","42"]],"ExecutionDriver":"native-0.2","ID":"TNFL:OUH3:64IZ:NKRR:DUQG:72ZE:5NGU:V7Z5:CH2J:CVRT:MIR6:MJQH","IPv4Forwarding":1,"Images":26,"IndexServerAddress":"https://index.docker.io/v1/","InitPath":"/usr/local/bin/docker","InitSha1":"","KernelVersion":"3.16.7-tinycore64","Labels":null,"MemTotal":4150849536,"MemoryLimit":1,"NCPU":8,"NEventsListener":0,"NFd":27,"NGoroutines":40,"Name":"boot2docker","OperatingSystem":"Boot2Docker 1.4.0 (TCL 5.4); master : 69cf398 - Fri Dec 12 01:15:02 UTC 2014","SwapLimit":1}
    http_version: 
  recorded_at: Tue, 16 Dec 2014 22:02:40 GMT
recorded_with: VCR 2.9.3
