---
http_interactions:
- request:
    method: post
    uri: "<DOCKER_HOST>/v1.16/images/create?fromImage=debian%3Awheezy"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.17.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Tue, 16 Dec 2014 22:02:22 GMT
    body:
      encoding: UTF-8
      string: "{\"status\":\"The image you are pulling has been verified\",\"id\":\"debian:wheezy\"}\r\n{\"status\":\"Already
        exists\",\"progressDetail\":{},\"id\":\"511136ea3c5a\"}{\"status\":\"Already
        exists\",\"progressDetail\":{},\"id\":\"f10807909bc5\"}{\"status\":\"Already
        exists\",\"progressDetail\":{},\"id\":\"f6fab3b798be\"}{\"status\":\"Status:
        Image is up to date for debian:wheezy\"}\r\n"
    http_version: 
  recorded_at: Tue, 16 Dec 2014 22:02:22 GMT
- request:
    method: post
    uri: "<DOCKER_HOST>/v1.16/containers/create"
    body:
      encoding: UTF-8
      string: '{"Image":"f6fab3b798be","Cmd":["pwd"]}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.17.0
      Content-Type:
      - application/json
  response:
    status:
      code: 201
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Tue, 16 Dec 2014 22:02:22 GMT
      Content-Length:
      - '90'
    body:
      encoding: UTF-8
      string: |
        {"Id":"0680477184a13aad38fcc8022e67f77a94634e030a8f58b76668fb7d5b866eec","Warnings":null}
    http_version: 
  recorded_at: Tue, 16 Dec 2014 22:02:22 GMT
- request:
    method: post
    uri: "<DOCKER_HOST>/v1.16/containers/0680477184a13aad38fcc8022e67f77a94634e030a8f58b76668fb7d5b866eec/start"
    body:
      encoding: UTF-8
      string: "{}"
    headers:
      User-Agent:
      - Swipely/Docker-API 1.17.0
      Content-Type:
      - application/json
  response:
    status:
      code: 204
      message: 
    headers:
      Date:
      - Tue, 16 Dec 2014 22:02:23 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 16 Dec 2014 22:02:22 GMT
- request:
    method: get
    uri: "<DOCKER_HOST>/v1.16/containers/0680477184a13aad38fcc8022e67f77a94634e030a8f58b76668fb7d5b866eec/logs?stdout=true"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.17.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Date:
      - Tue, 16 Dec 2014 22:02:23 GMT
      Content-Type:
      - application/octet-stream
    body:
      encoding: UTF-8
      string: !binary |-
        AQAAAAAAAAIvCg==
    http_version: 
  recorded_at: Tue, 16 Dec 2014 22:02:22 GMT
- request:
    method: post
    uri: "<DOCKER_HOST>/v1.16/containers/0680477184a13aad38fcc8022e67f77a94634e030a8f58b76668fb7d5b866eec/wait"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.17.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Tue, 16 Dec 2014 22:02:23 GMT
      Content-Length:
      - '17'
    body:
      encoding: UTF-8
      string: |
        {"StatusCode":0}
    http_version: 
  recorded_at: Tue, 16 Dec 2014 22:02:23 GMT
- request:
    method: delete
    uri: "<DOCKER_HOST>/v1.16/containers/0680477184a13aad38fcc8022e67f77a94634e030a8f58b76668fb7d5b866eec"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.17.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 204
      message: 
    headers:
      Date:
      - Tue, 16 Dec 2014 22:02:23 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 16 Dec 2014 22:02:23 GMT
recorded_with: VCR 2.9.3
