---
http_interactions:
- request:
    method: post
    uri: "<DOCKER_HOST>/v1.16/images/create?fromImage=debian%3Awheezy"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Swipely/Docker-API 1.23.0
      Content-Type:
      - text/plain
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Server:
      - Docker/1.9.0 (linux)
      Date:
      - Fri, 20 Nov 2015 16:40:13 GMT
    body:
      encoding: UTF-8
      string: "{\"status\":\"Pulling from library/debian\",\"id\":\"wheezy\"}\r\n{\"status\":\"Digest:
        sha256:913916fa02a58cde97ea6dbbdd009026c7910861a243b78c151d04bc1d23f39e\"}\r\n{\"status\":\"Status:
        Image is up to date for debian:wheezy\"}\r\n"
    http_version: 
  recorded_at: Fri, 20 Nov 2015 16:40:13 GMT
- request:
    method: post
    uri: "<DOCKER_HOST>/v1.16/containers/create"
    body:
      encoding: UTF-8
      string: '{"Image":"wheezy","Cmd":["pwd"]}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.23.0
      Content-Type:
      - application/json
  response:
    status:
      code: 404
      message: 
    headers:
      Content-Type:
      - text/plain; charset=utf-8
      Server:
      - Docker/1.9.0 (linux)
      Date:
      - Fri, 20 Nov 2015 16:40:13 GMT
      Content-Length:
      - '29'
    body:
      encoding: UTF-8
      string: |
        No such image: wheezy:latest
    http_version: 
  recorded_at: Fri, 20 Nov 2015 16:40:13 GMT
- request:
    method: post
    uri: "<DOCKER_HOST>/v1.16/containers/create"
    body:
      encoding: UTF-8
      string: '{"Image":"wheezy","Cmd":["pwd"]}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.23.0
      Content-Type:
      - application/json
  response:
    status:
      code: 404
      message: 
    headers:
      Content-Type:
      - text/plain; charset=utf-8
      Server:
      - Docker/1.9.0 (linux)
      Date:
      - Fri, 20 Nov 2015 16:40:13 GMT
      Content-Length:
      - '29'
    body:
      encoding: UTF-8
      string: |
        No such image: wheezy:latest
    http_version: 
  recorded_at: Fri, 20 Nov 2015 16:40:13 GMT
recorded_with: VCR 3.0.0
