---
http_interactions:
- request:
    method: post
    uri: "<DOCKER_HOST>/v1.16/auth"
    body:
      encoding: UTF-8
      string: '{"username":"<USERNAME>","password":"<PASSWORD>","email":"<EMAIL>","serveraddress":"https://index.docker.io/v1/"}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.17.0
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Tue, 16 Dec 2014 22:02:42 GMT
      Content-Length:
      - '29'
    body:
      encoding: UTF-8
      string: |
        {"Status":"Login Succeeded"}
    http_version: 
  recorded_at: Tue, 16 Dec 2014 22:02:42 GMT
recorded_with: VCR 2.9.3
